/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.tft.myoffice;

public final class R {
    public static final class array {
        public static final int bands=0x7f040002;
        public static final int colors=0x7f040000;
        public static final int planets=0x7f040001;
    }
    public static final class attr {
        public static final int text=0x7f010000;
        public static final int textColor=0x7f010001;
        public static final int textSize=0x7f010002;
    }
    public static final class color {
        public static final int alluminium_clear=0x7f05000c;
        public static final int alluminium_dark=0x7f05000e;
        public static final int alluminium_intense=0x7f05000d;
        /**  
			// TANGO Color Palette
	
         */
        public static final int butter_clear=0x7f050000;
        public static final int butter_dark=0x7f050002;
        public static final int butter_intense=0x7f050001;
        public static final int chamaleon_clear=0x7f050003;
        public static final int chamaleon_dark=0x7f050005;
        public static final int chamaleon_intense=0x7f050004;
        public static final int grey_clear=0x7f05000f;
        public static final int grey_dark=0x7f050011;
        public static final int grey_intense=0x7f050010;
        public static final int scarlet_red_clear=0x7f050006;
        public static final int scarlet_red_dark=0x7f050008;
        public static final int scarlet_red_intense=0x7f050007;
        public static final int sky_blu_clear=0x7f050009;
        public static final int sky_blu_dark=0x7f05000b;
        public static final int sky_blu_intense=0x7f05000a;
    }
    public static final class drawable {
        public static final int allert16x16=0x7f020000;
        public static final int appointementend16x16=0x7f020001;
        public static final int appointementstart16x16=0x7f020002;
        public static final int appointementstartclose16x16=0x7f020003;
        public static final int appointementstartopen16x16=0x7f020004;
        public static final int appointmentnew32x32=0x7f020005;
        public static final int background=0x7f020006;
        public static final int background2=0x7f020007;
        public static final int blue=0x7f020042;
        public static final int button_background48x48=0x7f020008;
        public static final int contact_list_background=0x7f020009;
        public static final int dbarrleft16x16=0x7f02000a;
        public static final int ferrai=0x7f02000b;
        public static final int go16x16=0x7f02000c;
        public static final int go32x32=0x7f02000d;
        public static final int green=0x7f020043;
        public static final int icon=0x7f02000e;
        public static final int icon_calendar=0x7f02000f;
        public static final int icon_complete=0x7f020010;
        public static final int icon_contacts=0x7f020011;
        public static final int icon_logo=0x7f020012;
        public static final int icon_notes=0x7f020013;
        public static final int icon_sync1_dark=0x7f020014;
        public static final int icon_sync2_dark=0x7f020015;
        public static final int icon_sync3_dark=0x7f020016;
        public static final int icon_sync4_dark=0x7f020017;
        public static final int icon_sync_all_blue=0x7f020018;
        public static final int icon_tasks=0x7f020019;
        public static final int list_add16x16=0x7f02001a;
        public static final int list_remove16x16=0x7f02001b;
        public static final int logo=0x7f02001c;
        public static final int mail_forward=0x7f02001d;
        public static final int moin1_8x8=0x7f02001e;
        public static final int moin7_8x8=0x7f02001f;
        public static final int moin7b_16x16=0x7f020020;
        public static final int moin7c_16x16=0x7f020021;
        public static final int moins1_16x16=0x7f020022;
        public static final int moins1_22x22=0x7f020023;
        public static final int moins7_16x16=0x7f020024;
        public static final int moins7_22x22=0x7f020025;
        public static final int office_calendar=0x7f020026;
        public static final int office_calendar16x16=0x7f020027;
        public static final int people32x32=0x7f020028;
        public static final int people_add16x16=0x7f020029;
        public static final int people_add32x32=0x7f02002a;
        public static final int people_remove16x16=0x7f02002b;
        public static final int people_remove32x32=0x7f02002c;
        public static final int plus1_16x16=0x7f02002d;
        public static final int plus1_22x22=0x7f02002e;
        public static final int plus1_8x8=0x7f02002f;
        public static final int plus7_16x16=0x7f020030;
        public static final int plus7_22x22=0x7f020031;
        public static final int plus7_8x8=0x7f020032;
        public static final int questionmark16x16=0x7f020033;
        public static final int red=0x7f020041;
        public static final int screen_background_black=0x7f020045;
        public static final int settings=0x7f020034;
        public static final int shape_1=0x7f020035;
        public static final int stop16x16=0x7f020036;
        public static final int stop32x32=0x7f020037;
        public static final int sync_all_shape=0x7f020038;
        public static final int sync_all_shape_over=0x7f020039;
        public static final int sync_shape=0x7f02003a;
        public static final int sync_shape_2=0x7f02003b;
        public static final int sync_shape_over=0x7f02003c;
        public static final int texteditor32x32=0x7f02003d;
        public static final int tft01icon=0x7f02003e;
        public static final int translucent_background=0x7f020046;
        public static final int transparent_background=0x7f020047;
        public static final int trash16x16=0x7f02003f;
        public static final int trash32x32=0x7f020040;
        public static final int yellow=0x7f020044;
    }
    public static final class id {
        public static final int Call=0x7f06000d;
        public static final int DateSetUp=0x7f060018;
        public static final int DateTim=0x7f060013;
        public static final int Del=0x7f06000e;
        public static final int DurationSetUp=0x7f06001e;
        public static final int EndSetUp=0x7f06001c;
        public static final int MeetingDescription=0x7f060023;
        public static final int MeetingObject=0x7f060022;
        public static final int MeetingViewDate=0x7f060017;
        public static final int MeetingViewDateTitle=0x7f060014;
        public static final int MeetingViewDuration=0x7f06001d;
        public static final int MeetingViewEnd=0x7f06001b;
        public static final int MeetingViewFixed=0x7f06001f;
        public static final int MeetingViewStart=0x7f060019;
        public static final int MeetingViewStartTitle=0x7f060015;
        public static final int Name=0x7f06000c;
        public static final int Object=0x7f060021;
        public static final int StartSetUp=0x7f06001a;
        public static final int Status=0x7f06000b;
        public static final int Text1=0x7f060009;
        public static final int Text2=0x7f06000a;
        public static final int TimeSetUp=0x7f060011;
        public static final int ToolBar=0x7f06000f;
        public static final int ViewObjectiveDetail=0x7f060020;
        public static final int ViewPeopleList=0x7f060024;
        public static final int ViewTimeSetUp=0x7f060016;
        public static final int body2=0x7f06002c;
        public static final int btnAddPeople=0x7f060025;
        public static final int btnObjectiveDetail=0x7f060010;
        public static final int btnPeopleList=0x7f060012;
        public static final int btnRemovePeople=0x7f060026;
        public static final int calendar_arrow=0x7f060033;
        public static final int calendar_shape=0x7f060031;
        public static final int cancel=0x7f060003;
        public static final int cbxSelectItem=0x7f060001;
        public static final int confirm=0x7f060004;
        public static final int contacts_arrow=0x7f060030;
        public static final int contacts_shape=0x7f06002e;
        public static final int from=0x7f060029;
        public static final int image=0x7f060006;
        public static final int imagetext=0x7f060007;
        public static final int notes_arrow=0x7f060038;
        public static final int notes_shape=0x7f060005;
        public static final int password=0x7f060028;
        public static final int send=0x7f06002d;
        public static final int snack=0x7f060000;
        public static final int subject2=0x7f06002b;
        public static final int sync_message_calendar=0x7f060032;
        public static final int sync_message_contacts=0x7f06002f;
        public static final int sync_message_notes=0x7f060037;
        public static final int sync_message_tasks=0x7f060035;
        public static final int tasks_arrow=0x7f060036;
        public static final int tasks_shape=0x7f060034;
        public static final int to=0x7f06002a;
        public static final int toolbar=0x7f060008;
        public static final int txtView=0x7f060002;
        public static final int userid=0x7f060027;
    }
    public static final class layout {
        public static final int contactlistrow=0x7f030000;
        public static final int contactslistview=0x7f030001;
        public static final int customdialog=0x7f030002;
        public static final int imagegrid=0x7f030003;
        public static final int imageview=0x7f030004;
        public static final int meetingdaylist=0x7f030005;
        public static final int meetingdayrows=0x7f030006;
        public static final int meetingpeoplelistrow=0x7f030007;
        public static final int meetingview=0x7f030008;
        public static final int sendmailtestview=0x7f030009;
        public static final int setupcontent=0x7f03000a;
    }
    public static final class string {
        /**  =============================== 
  Agenda Message  
 =============================== 
         */
        public static final int Exception_meeting_conflict=0x7f070187;
        public static final int activity_alarm_controller=0x7f070046;
        public static final int activity_alarm_service=0x7f070051;
        public static final int activity_contacts_filter=0x7f070059;
        public static final int activity_forwarding=0x7f070011;
        /**  =============================== 
  app/activity examples strings  
 =============================== 
         */
        public static final int activity_hello_world=0x7f070001;
        public static final int activity_local_sample=0x7f070057;
        public static final int activity_local_service_binding=0x7f070023;
        public static final int activity_local_service_controller=0x7f07001f;
        public static final int activity_persistent=0x7f07000b;
        public static final int activity_receive_result=0x7f07000d;
        public static final int activity_redirect=0x7f070015;
        public static final int activity_remote_service_binding=0x7f07002e;
        public static final int activity_remote_service_controller=0x7f07002c;
        public static final int activity_resources=0x7f070066;
        public static final int activity_sample_code=0x7f070000;
        public static final int activity_save_restore=0x7f070006;
        public static final int activity_service_start_arguments_controller=0x7f070037;
        /**  ============================== 
  app/content examples strings  
 ============================== 
         */
        public static final int activity_styled_text=0x7f070061;
        public static final int activity_themes=0x7f070065;
        public static final int activity_translucent=0x7f070003;
        public static final int activity_translucent_fancy=0x7f070005;
        public static final int alarm_controller=0x7f070047;
        public static final int alarm_service=0x7f070052;
        public static final int alarm_service_finished=0x7f07004f;
        public static final int alarm_service_label=0x7f070050;
        public static final int alarm_service_scheduled=0x7f070055;
        public static final int alarm_service_started=0x7f07004e;
        public static final int alarm_service_unscheduled=0x7f070056;
        /**  ================================== 
  initial strings for layout files  
 ================================== 
         */
        public static final int animation_1_instructions=0x7f07008b;
        public static final int animation_2_instructions=0x7f070090;
        public static final int animation_2_text_1=0x7f07008c;
        public static final int animation_2_text_2=0x7f07008d;
        public static final int animation_2_text_3=0x7f07008e;
        public static final int animation_2_text_4=0x7f07008f;
        public static final int apply=0x7f07001b;
        public static final int autocomplete_1_country=0x7f070092;
        public static final int autocomplete_1_focus=0x7f070093;
        public static final int autocomplete_1_instructions=0x7f070091;
        public static final int autocomplete_2_country=0x7f070094;
        public static final int autocomplete_2_focus=0x7f070095;
        public static final int autocomplete_3_button=0x7f07009e;
        public static final int autocomplete_3_button_1=0x7f070096;
        public static final int autocomplete_3_button_2=0x7f070097;
        public static final int autocomplete_3_button_3=0x7f070098;
        public static final int autocomplete_3_button_4=0x7f070099;
        public static final int autocomplete_3_button_5=0x7f07009a;
        public static final int autocomplete_3_button_6=0x7f07009b;
        public static final int autocomplete_3_button_7=0x7f07009c;
        public static final int autocomplete_3_button_8=0x7f07009d;
        public static final int autocomplete_3_country=0x7f07009f;
        public static final int autocomplete_4_instructions=0x7f0700a0;
        public static final int autocomplete_4_message=0x7f0700a2;
        public static final int autocomplete_4_name=0x7f0700a1;
        public static final int autocomplete_5_hint=0x7f0700a4;
        public static final int autocomplete_5_instructions=0x7f0700a3;
        public static final int autocomplete_5_name=0x7f0700a5;
        public static final int baseline_1_bigger=0x7f0700a8;
        public static final int baseline_1_button=0x7f0700a7;
        public static final int baseline_1_label=0x7f0700a6;
        public static final int baseline_2_bigger=0x7f0700ab;
        public static final int baseline_2_button=0x7f0700aa;
        public static final int baseline_2_label=0x7f0700a9;
        public static final int baseline_3_bigger=0x7f0700ae;
        public static final int baseline_3_button=0x7f0700ad;
        public static final int baseline_3_label=0x7f0700ac;
        public static final int baseline_4_bigger=0x7f0700b1;
        public static final int baseline_4_button=0x7f0700b0;
        public static final int baseline_4_label=0x7f0700af;
        public static final int baseline_4_label_2=0x7f0700b2;
        public static final int baseline_4_label_3=0x7f0700b3;
        public static final int baseline_5_bigger=0x7f0700b6;
        public static final int baseline_5_button=0x7f0700b5;
        public static final int baseline_5_label=0x7f0700b4;
        public static final int baseline_5_label_2=0x7f0700b7;
        public static final int baseline_5_label_3=0x7f0700b8;
        public static final int baseline_6_baseline=0x7f0700ba;
        public static final int baseline_6_multi_line=0x7f0700b9;
        public static final int baseline_7_fat=0x7f0700bb;
        public static final int baseline_7_lean=0x7f0700bc;
        public static final int baseline_nested_1_label=0x7f0700bd;
        public static final int bind_service=0x7f070025;
        public static final int clear_text=0x7f070018;
        public static final int contacts_filter=0x7f07005a;
        public static final int controls_1_checkbox_1=0x7f0700bf;
        public static final int controls_1_checkbox_2=0x7f0700c0;
        public static final int controls_1_radiobutton_1=0x7f0700c1;
        public static final int controls_1_radiobutton_2=0x7f0700c2;
        public static final int controls_1_save=0x7f0700be;
        public static final int corky=0x7f07000f;
        public static final int custom_notification=0x7f07006e;
        public static final int custom_notification_button=0x7f07006f;
        public static final int date_widgets_example_dateDisplay_text=0x7f070184;
        public static final int date_widgets_example_pickDate_text=0x7f070186;
        public static final int date_widgets_example_pickTime_text=0x7f070185;
        public static final int focus_1_message=0x7f0700c3;
        public static final int focus_1_placeholder=0x7f0700c4;
        public static final int focus_2_jump=0x7f0700c6;
        public static final int focus_2_left=0x7f0700c5;
        public static final int focus_2_right=0x7f0700c7;
        public static final int focus_3_bottom=0x7f0700cb;
        public static final int focus_3_left=0x7f0700c8;
        public static final int focus_3_right=0x7f0700c9;
        public static final int focus_3_top=0x7f0700ca;
        public static final int forward_target=0x7f070014;
        public static final int forwarding=0x7f070012;
        public static final int found_stale_xmpp_service=0x7f070043;
        public static final int gallery_2_text=0x7f0700cc;
        public static final int go=0x7f070013;
        public static final int google_login_username_text=0x7f070177;
        public static final int googlelogin_bad_login=0x7f0700ce;
        public static final int googlelogin_clear=0x7f0700cf;
        /**  ============================== 
  GoogleLogin examples strings  
 ============================== 
         */
        public static final int googlelogin_err=0x7f07008a;
        public static final int googlelogin_login=0x7f0700cd;
        public static final int googlelogin_user=0x7f0700d0;
        public static final int hello_world=0x7f070002;
        public static final int imcoming_message_view_message2_text=0x7f07017b;
        public static final int incoming_message_info_message_text=0x7f070179;
        public static final int incoming_message_notify_text=0x7f070178;
        public static final int incoming_message_view_message_text=0x7f07017a;
        public static final int initial_text=0x7f07000a;
        public static final int invalid_username=0x7f070040;
        public static final int kill_process=0x7f070030;
        public static final int linear_layout_1_bottom=0x7f0700d3;
        public static final int linear_layout_1_middle=0x7f0700d2;
        public static final int linear_layout_1_top=0x7f0700d1;
        public static final int linear_layout_2_bottom=0x7f0700d6;
        public static final int linear_layout_2_middle=0x7f0700d5;
        public static final int linear_layout_2_top=0x7f0700d4;
        public static final int linear_layout_3_bottom=0x7f0700d9;
        public static final int linear_layout_3_middle=0x7f0700d8;
        public static final int linear_layout_3_top=0x7f0700d7;
        public static final int linear_layout_5_cancel=0x7f0700db;
        public static final int linear_layout_5_instructions=0x7f0700da;
        public static final int linear_layout_5_ok=0x7f0700dc;
        public static final int linear_layout_6_four=0x7f0700e0;
        public static final int linear_layout_6_one=0x7f0700dd;
        public static final int linear_layout_6_three=0x7f0700df;
        public static final int linear_layout_6_two=0x7f0700de;
        public static final int linear_layout_7_big=0x7f0700e2;
        public static final int linear_layout_7_small=0x7f0700e1;
        public static final int linear_layout_7_wrap=0x7f0700e3;
        public static final int linear_layout_8_a=0x7f0700e4;
        public static final int linear_layout_8_b=0x7f0700e5;
        public static final int linear_layout_8_bottom=0x7f07007e;
        public static final int linear_layout_8_c=0x7f0700e6;
        public static final int linear_layout_8_center=0x7f070080;
        public static final int linear_layout_8_horizontal=0x7f07007b;
        public static final int linear_layout_8_left=0x7f07007f;
        public static final int linear_layout_8_middle=0x7f07007d;
        public static final int linear_layout_8_right=0x7f070081;
        public static final int linear_layout_8_top=0x7f07007c;
        /**  ============================ 
  app/views examples strings  
 ============================ 
         */
        public static final int linear_layout_8_vertical=0x7f07007a;
        public static final int linear_layout_9_button=0x7f0700e7;
        public static final int link_text=0x7f0700e8;
        public static final int list_7_nothing=0x7f070082;
        public static final int list_8_clear_photos=0x7f0700ea;
        public static final int list_8_new_photo=0x7f0700e9;
        public static final int list_8_no_photos=0x7f0700eb;
        public static final int local_sample=0x7f070058;
        public static final int local_service_binding=0x7f070024;
        public static final int local_service_connected=0x7f070027;
        public static final int local_service_controller=0x7f070020;
        public static final int local_service_disconnected=0x7f070028;
        public static final int local_service_label=0x7f07001e;
        public static final int local_service_started=0x7f07001c;
        public static final int local_service_stopped=0x7f07001d;
        public static final int log_text_box_1_add_text=0x7f07017d;
        public static final int log_text_box_1_do_nothing_text=0x7f07017c;
        public static final int long_notification=0x7f070068;
        public static final int long_notification_text=0x7f07005e;
        public static final int menu_delete_meeting=0x7f070189;
        /**  =============================== 
  Agenda Menu' items  
 =============================== 
         */
        public static final int menu_insert_meeting=0x7f070188;
        public static final int menu_update_meeting=0x7f07018a;
        public static final int new_text=0x7f070019;
        public static final int no_saves_state=0x7f070009;
        public static final int notify_with_text_long_notify_text=0x7f07017e;
        public static final int notify_with_text_short_notify_text=0x7f07017f;
        public static final int notifying_service_controller=0x7f070060;
        public static final int one_shot_alarm=0x7f070048;
        public static final int one_shot_received=0x7f070044;
        public static final int one_shot_scheduled=0x7f07004b;
        public static final int persistent_msg=0x7f07000c;
        public static final int pick_image=0x7f07005c;
        public static final int pick_image_label=0x7f07005b;
        public static final int pick_result=0x7f07000e;
        public static final int progressbar_1_minus=0x7f0700ed;
        public static final int progressbar_1_plus=0x7f0700ec;
        public static final int progressbar_3_indeterminate=0x7f0700ef;
        public static final int progressbar_3_indeterminate_no_title=0x7f0700f0;
        public static final int progressbar_3_progress=0x7f0700ee;
        public static final int progressbar_4_toggle=0x7f0700f1;
        public static final int radio_group_1_all=0x7f0700f5;
        public static final int radio_group_1_breakfast=0x7f0700f2;
        public static final int radio_group_1_clear=0x7f0700f7;
        public static final int radio_group_1_dinner=0x7f0700f4;
        public static final int radio_group_1_lunch=0x7f0700f3;
        public static final int radio_group_1_selection=0x7f0700f6;
        public static final int radio_group_none=0x7f070085;
        public static final int radio_group_selection=0x7f070084;
        public static final int radio_group_snack=0x7f070083;
        public static final int receive_result_instructions=0x7f0700f8;
        public static final int receive_result_result=0x7f0700f9;
        public static final int redirect_enter=0x7f070016;
        public static final int redirect_getter=0x7f07001a;
        public static final int redirect_main=0x7f070017;
        public static final int relative_layout_1_bottom=0x7f0700fb;
        public static final int relative_layout_1_center=0x7f0700fc;
        public static final int relative_layout_1_top=0x7f0700fa;
        public static final int relative_layout_2_cancel=0x7f0700ff;
        public static final int relative_layout_2_instructions=0x7f0700fd;
        public static final int relative_layout_2_ok=0x7f0700fe;
        public static final int remote_call_failed=0x7f070033;
        public static final int remote_service_binding=0x7f07002f;
        public static final int remote_service_connected=0x7f070031;
        public static final int remote_service_controller=0x7f07002d;
        public static final int remote_service_disconnected=0x7f070032;
        public static final int remote_service_label=0x7f07002b;
        public static final int remote_service_started=0x7f070029;
        public static final int remote_service_stopped=0x7f07002a;
        public static final int repeating_received=0x7f070045;
        public static final int repeating_scheduled=0x7f07004c;
        public static final int repeating_unscheduled=0x7f07004d;
        public static final int save_restore_msg=0x7f070007;
        public static final int saves_state=0x7f070008;
        public static final int scroll_view_1_button_1=0x7f070101;
        public static final int scroll_view_1_button_2=0x7f070103;
        public static final int scroll_view_1_button_3=0x7f070105;
        public static final int scroll_view_1_button_4=0x7f070107;
        public static final int scroll_view_1_button_5=0x7f070109;
        public static final int scroll_view_1_button_6=0x7f07010b;
        public static final int scroll_view_1_text_1=0x7f070100;
        public static final int scroll_view_1_text_2=0x7f070102;
        public static final int scroll_view_1_text_3=0x7f070104;
        public static final int scroll_view_1_text_4=0x7f070106;
        public static final int scroll_view_1_text_5=0x7f070108;
        public static final int scroll_view_1_text_6=0x7f07010a;
        public static final int scroll_view_2_button_1=0x7f07010d;
        public static final int scroll_view_2_text_1=0x7f07010c;
        public static final int scrollbar_1_text=0x7f07010e;
        public static final int scrollbar_2_text=0x7f07010f;
        public static final int send_message=0x7f07003f;
        public static final int service_arguments_started=0x7f070034;
        public static final int service_arguments_stopped=0x7f070035;
        public static final int service_start_arguments_controller=0x7f070038;
        public static final int service_start_arguments_label=0x7f070036;
        public static final int short_bottom_notification=0x7f07006a;
        public static final int short_center_notification=0x7f07006b;
        public static final int short_left_notification=0x7f07006c;
        /**  =================================== 
  app/notification examples strings  
 =================================== 
         */
        public static final int short_notification=0x7f070067;
        public static final int short_notification_text=0x7f07005d;
        public static final int short_right_notification=0x7f07006d;
        public static final int short_top_notification=0x7f070069;
        public static final int spinner_1_color=0x7f070110;
        public static final int spinner_1_planet=0x7f070111;
        public static final int start1_service=0x7f070039;
        public static final int start2_service=0x7f07003a;
        public static final int start3_service=0x7f07003b;
        public static final int start_alarm_service=0x7f070053;
        public static final int start_repeating_alarm=0x7f070049;
        public static final int start_service=0x7f070021;
        public static final int status_bar_notification_title=0x7f07005f;
        public static final int status_bar_notifications_clear=0x7f070079;
        public static final int status_bar_notifications_happy=0x7f070073;
        public static final int status_bar_notifications_happy_message=0x7f070076;
        public static final int status_bar_notifications_icons_and_marquee=0x7f070071;
        public static final int status_bar_notifications_icons_only=0x7f070070;
        public static final int status_bar_notifications_ok=0x7f070074;
        public static final int status_bar_notifications_ok_message=0x7f070077;
        public static final int status_bar_notifications_remote_views=0x7f070072;
        public static final int status_bar_notifications_sad=0x7f070075;
        public static final int status_bar_notifications_sad_message=0x7f070078;
        public static final int stop_alarm_service=0x7f070054;
        public static final int stop_repeating_alarm=0x7f07004a;
        public static final int stop_service=0x7f070022;
        public static final int styled_text=0x7f070063;
        public static final int styled_text_prog=0x7f070064;
        public static final int styled_text_rsrc=0x7f070062;
        public static final int table_layout_10_cancel=0x7f070166;
        public static final int table_layout_10_login=0x7f070167;
        public static final int table_layout_10_password=0x7f070165;
        public static final int table_layout_10_password_text=0x7f070180;
        public static final int table_layout_10_user=0x7f070164;
        public static final int table_layout_10_username_text=0x7f070181;
        public static final int table_layout_12_a=0x7f070168;
        public static final int table_layout_12_b=0x7f070169;
        public static final int table_layout_12_c=0x7f07016a;
        public static final int table_layout_12_d=0x7f07016b;
        public static final int table_layout_12_e=0x7f07016c;
        public static final int table_layout_12_f=0x7f07016d;
        public static final int table_layout_12_g=0x7f07016e;
        public static final int table_layout_12_h=0x7f07016f;
        public static final int table_layout_1_open=0x7f070114;
        public static final int table_layout_1_open_shortcut=0x7f070115;
        public static final int table_layout_1_quit=0x7f070118;
        public static final int table_layout_1_quit_shortcut=0x7f070119;
        public static final int table_layout_1_save=0x7f070116;
        public static final int table_layout_1_save_shortcut=0x7f070117;
        public static final int table_layout_1_star=0x7f070112;
        public static final int table_layout_1_triple_star=0x7f070113;
        public static final int table_layout_2_open=0x7f07011c;
        public static final int table_layout_2_path_1=0x7f07011a;
        public static final int table_layout_2_path_2=0x7f07011b;
        public static final int table_layout_2_save=0x7f07011d;
        public static final int table_layout_2_save_all=0x7f07011e;
        public static final int table_layout_3_open=0x7f070121;
        public static final int table_layout_3_open_shortcut=0x7f070122;
        public static final int table_layout_3_quit=0x7f070126;
        public static final int table_layout_3_quit_shortcut=0x7f070127;
        public static final int table_layout_3_save=0x7f070123;
        public static final int table_layout_3_save_shortcut=0x7f070124;
        public static final int table_layout_3_star=0x7f07011f;
        public static final int table_layout_3_too_long=0x7f070125;
        public static final int table_layout_3_triple_star=0x7f070120;
        public static final int table_layout_4_open=0x7f070128;
        public static final int table_layout_4_open_shortcut=0x7f070129;
        public static final int table_layout_4_save=0x7f07012a;
        public static final int table_layout_4_save_shortcut=0x7f07012b;
        public static final int table_layout_5_export=0x7f070133;
        public static final int table_layout_5_export_shortcut=0x7f070134;
        public static final int table_layout_5_import=0x7f070132;
        public static final int table_layout_5_open=0x7f07012c;
        public static final int table_layout_5_open_shortcut=0x7f07012d;
        public static final int table_layout_5_quit=0x7f070135;
        public static final int table_layout_5_save=0x7f07012e;
        public static final int table_layout_5_save_as=0x7f070130;
        public static final int table_layout_5_save_as_shortcut=0x7f070131;
        public static final int table_layout_5_save_shortcut=0x7f07012f;
        public static final int table_layout_6_export=0x7f07013e;
        public static final int table_layout_6_export_shortcut=0x7f07013f;
        public static final int table_layout_6_import=0x7f07013d;
        public static final int table_layout_6_open=0x7f070137;
        public static final int table_layout_6_open_shortcut=0x7f070138;
        public static final int table_layout_6_quit=0x7f070140;
        public static final int table_layout_6_save=0x7f070139;
        public static final int table_layout_6_save_as=0x7f07013b;
        public static final int table_layout_6_save_as_shortcut=0x7f07013c;
        public static final int table_layout_6_save_shortcut=0x7f07013a;
        public static final int table_layout_6_x=0x7f070136;
        public static final int table_layout_7_ctrlq=0x7f070087;
        public static final int table_layout_7_export=0x7f070149;
        public static final int table_layout_7_export_shortcut=0x7f07014a;
        public static final int table_layout_7_import=0x7f070148;
        public static final int table_layout_7_open=0x7f070142;
        public static final int table_layout_7_open_shortcut=0x7f070143;
        public static final int table_layout_7_quit=0x7f070086;
        public static final int table_layout_7_save=0x7f070144;
        public static final int table_layout_7_save_as=0x7f070146;
        public static final int table_layout_7_save_as_shortcut=0x7f070147;
        public static final int table_layout_7_save_shortcut=0x7f070145;
        public static final int table_layout_7_toggle_checkmarks=0x7f07014b;
        public static final int table_layout_7_toggle_shortcuts=0x7f07014c;
        public static final int table_layout_7_x=0x7f070141;
        public static final int table_layout_8_ctrlq=0x7f070089;
        public static final int table_layout_8_export=0x7f070155;
        public static final int table_layout_8_export_shortcut=0x7f070156;
        public static final int table_layout_8_import=0x7f070154;
        public static final int table_layout_8_open=0x7f07014e;
        public static final int table_layout_8_open_shortcut=0x7f07014f;
        public static final int table_layout_8_quit=0x7f070088;
        public static final int table_layout_8_save=0x7f070150;
        public static final int table_layout_8_save_as=0x7f070152;
        public static final int table_layout_8_save_as_shortcut=0x7f070153;
        public static final int table_layout_8_save_shortcut=0x7f070151;
        public static final int table_layout_8_toggle_stretch=0x7f070157;
        public static final int table_layout_8_x=0x7f07014d;
        public static final int table_layout_9_export=0x7f070161;
        public static final int table_layout_9_export_shortcut=0x7f070162;
        public static final int table_layout_9_import=0x7f070160;
        public static final int table_layout_9_open=0x7f070158;
        public static final int table_layout_9_open_shortcut=0x7f070159;
        public static final int table_layout_9_save=0x7f07015a;
        public static final int table_layout_9_save_all=0x7f07015e;
        public static final int table_layout_9_save_all_shortcut=0x7f07015f;
        public static final int table_layout_9_save_as=0x7f07015c;
        public static final int table_layout_9_save_as_shortcut=0x7f07015d;
        public static final int table_layout_9_save_shortcut=0x7f07015b;
        public static final int table_layout_9_toggle_shrink=0x7f070163;
        public static final int text_switcher_1_next_text=0x7f070182;
        public static final int ticker_1_instructions=0x7f070170;
        public static final int ticker_1_tickerText_text=0x7f070183;
        public static final int translucent_background=0x7f070004;
        public static final int unbind_service=0x7f070026;
        public static final int violet=0x7f070010;
        public static final int visibility_1_gone=0x7f070176;
        public static final int visibility_1_invis=0x7f070175;
        public static final int visibility_1_view_1=0x7f070171;
        public static final int visibility_1_view_2=0x7f070172;
        public static final int visibility_1_view_3=0x7f070173;
        public static final int visibility_1_vis=0x7f070174;
        public static final int xmpp_data_message_sender=0x7f07003c;
        public static final int xmpp_send_message_sender_desc=0x7f07003d;
        public static final int xmpp_service_not_connected=0x7f070041;
        public static final int xmpp_session_not_found=0x7f070042;
        public static final int xmpp_username=0x7f07003e;
    }
    public static final class style {
        /**  About Activity Style 
         */
        public static final int about_layout=0x7f08001a;
        public static final int about_logo=0x7f08001c;
        /**  Buttons style 
         */
        public static final int action_button=0x7f08001e;
        public static final int copy_text=0x7f08001b;
        public static final int licence_text=0x7f08001d;
        /**  Main Activity Style 
         */
        public static final int main_layout=0x7f080001;
        public static final int pref_button_raw=0x7f080019;
        public static final int pref_edit_text=0x7f080018;
        public static final int pref_label=0x7f080017;
        /**  Preferences Activity Style 
         */
        public static final int pref_layout=0x7f080013;
        public static final int pref_table_layout=0x7f080016;
        public static final int pref_title_layout=0x7f080014;
        public static final int pref_title_shape=0x7f080015;
        /**  ScrollView style 
         */
        public static final int scroll_style=0x7f080000;
        public static final int sync_all_arrow=0x7f080008;
        public static final int sync_all_icon_logo=0x7f080006;
        /**  Main Activity Sync All Style 
         */
        public static final int sync_all_layout=0x7f080002;
        public static final int sync_all_linear_lh=0x7f080004;
        public static final int sync_all_linear_lv=0x7f080005;
        public static final int sync_all_shape=0x7f080003;
        public static final int sync_all_title=0x7f080007;
        public static final int sync_arrow=0x7f080012;
        public static final int sync_icon=0x7f08000d;
        /**  Main Activity Sync Style 
         */
        public static final int sync_layout=0x7f080009;
        public static final int sync_linear_lh=0x7f08000c;
        public static final int sync_linear_lv=0x7f08000e;
        public static final int sync_linear_lv_2=0x7f08000f;
        public static final int sync_message=0x7f080011;
        public static final int sync_shape=0x7f08000a;
        public static final int sync_shape_2=0x7f08000b;
        public static final int sync_title=0x7f080010;
    }
    public static final class styleable {
        /** Attributes that can be used with a LabelView.
           <p>Includes the following attributes:</p>
           <table border="2" width="85%" align="center" frame="hsides" rules="all" cellpadding="5">
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute<th>Summary</tr>
           <tr><th><code>{@link #LabelView_text com.tft.myoffice:text}</code><td></tr>
           <tr><th><code>{@link #LabelView_textColor com.tft.myoffice:textColor}</code><td></tr>
           <tr><th><code>{@link #LabelView_textSize com.tft.myoffice:textSize}</code><td></tr>
           </table>
           @see #LabelView_text
           @see #LabelView_textColor
           @see #LabelView_textSize
         */
        public static final int[] LabelView = {
            0x7f010000, 0x7f010001, 0x7f010002
        };
        /**
          <p>This symbol is the offset where the {@link com.tft.myoffice.R.attr#text}
          attribute's value can be found in the {@link #LabelView} array.
          @attr name android:text
        */
        public static final int LabelView_text = 0;
        /**
          <p>This symbol is the offset where the {@link com.tft.myoffice.R.attr#textColor}
          attribute's value can be found in the {@link #LabelView} array.
          @attr name android:textColor
        */
        public static final int LabelView_textColor = 1;
        /**
          <p>This symbol is the offset where the {@link com.tft.myoffice.R.attr#textSize}
          attribute's value can be found in the {@link #LabelView} array.
          @attr name android:textSize
        */
        public static final int LabelView_textSize = 2;
    };
}
